
server:
  port: 7070

#配置日志
logging:
  level:
    com.javaoffers.**: DEBUG

spring:
  #配置应用名称
  application:
    name: mhbase
  #配置master数据库http://localhost/BaseDB/testDataSourceRoute
  datasource_master:
      url: jdbc:mysql://localhost:3306/base
      username: root
      password: zqbxcmj
      #readWriteSeparation: true #开启读写分离
      readDataSources: slaveBase, slaveBaseTow #指定读数据库

  #从数据库    
  datasource_slaves:
    -
      slavename: fit
      url: jdbc:mysql://localhost:3306/fit
      username: root
      password: zqbxcmj
    -
      slavename: exam
      url: jdbc:mysql://localhost:3306/exam
      username: root
      password: zqbxcmj
    -
      slavename: slaveBase
      url: jdbc:mysql://localhost:3306/base
      username: root
      password: zqbxcmj
    -
      slavename: slaveBaseTow
      url: jdbc:mysql://localhost:3306/base
      username: root
      password: zqbxcmj

#配置mybatis 
mybatis:
  #扫描mapper 文件路径
  mapper-locations : classpath*:/mybatis/**/*.xml
  configuration:
    #sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 
#配置eureka 
#eureka:
#  instance:
#    prefer-ip-address: true  
#  client:
#    service-url:
#      defaultZone : http://root:123@localhost:8761/eureka/

      

      
      
      
      
      
      